(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var aa=this||self;function k(a,b){a=a.split(".");var c=aa;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b};var l={};var m={},n=null;
function p(a){var b;void 0===b&&(b=0);if(!n){n={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));m[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===n[h]&&(n[h]=g)}}}b=m[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var w=a[f],x=a[f+1];h=a[f+2];g=b[w>>2];w=b[(w&3)<<4|x>>4];x=b[(x&15)<<2|h>>6];h=b[h&63];c[e++]=g+w+x+h}g=0;h=d;switch(a.length-f){case 2:g=
a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+h+d}return c.join("")};var q="undefined"!==typeof Uint8Array,r={};let t;var u=class{constructor(a){if(r!==r)throw Error("illegal external caller");this.v=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");}};const v=Symbol(void 0);function y(a,b){Object.isFrozen(a)||(v?a[v]|=b:void 0!==a.m?a.m|=b:Object.defineProperties(a,{m:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function z(a){let b;v?b=a[v]:b=a.m;return null==b?0:b}function A(a){y(a,1);return a}function B(a){return Array.isArray(a)?!!(z(a)&2):!1}function C(a){if(!Array.isArray(a))throw Error("cannot mark non-array as immutable");y(a,2)};function D(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var E=Object.freeze(A([]));function F(a){if(B(a.i))throw Error("Cannot mutate an immutable Message");}function G(a){return{value:a,configurable:!1,writable:!1,enumerable:!1}};function ba(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(q&&null!=a&&a instanceof Uint8Array)return p(a);if(a instanceof u){var b=a.v;b=null==b||"string"===typeof b?b:q&&b instanceof Uint8Array?p(b):null;return null==b?"":a.v=b}}}return a};function H(a,b=ca){return I(a,b)}function J(a,b){if(null!=a){if(Array.isArray(a))a=I(a,b);else if(D(a)){const c={};for(let d in a)c[d]=J(a[d],b);a=c}else a=b(a);return a}}function I(a,b){const c=a.slice();for(let d=0;d<c.length;d++)c[d]=J(c[d],b);Array.isArray(a)&&z(a)&1&&A(c);return c}function K(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a=ba(a);return Array.isArray(a)?H(a,K):a}function ca(a){return q&&null!=a&&a instanceof Uint8Array?new Uint8Array(a):a};function L(a){return a.h||(a.h=a.i[a.j+a.l]={})}function M(a,b,c=!1){return-1===b?null:b>=a.j?a.h?a.h[b]:void 0:c&&a.h&&(c=a.h[b],null!=c)?c:a.i[b+a.l]}function N(a,b,c,d=!1){F(a);b<a.j&&!d?a.i[b+a.l]=c:L(a)[b]=c}function O(a,b){a=M(a,b);return null==a?a:!!a}function da(a){a=M(a,3);return null==a?0:a}function ea(a){a=O(a,1);return null==a?!1:a}function P(a,b,c,d){F(a);c!==d?N(a,b,c):N(a,b,void 0,!1)}
function Q(a,b,c){if(-1===c)var d=null;else if(a.g||(a.g={}),d=a.g[c],!d){var e=M(a,c,!1);b=Array.isArray(e)?new b(e):void 0;void 0!=b&&(a.g[c]=b,B(a.i)&&C(b.i),d=b)}if(null==d)return d;B(d.i)&&!B(a.i)&&(d=d.u(l),N(a,c,d.i,!1),a.g[c]=d);return d};function R(a,b){if(null==b||""==b)return new a;b=JSON.parse(b);if(!Array.isArray(b))throw a=typeof b,Error("Expected to deserialize an Array but got "+("object"!=a?a:b?Array.isArray(b)?"array":a:"null")+": "+b);S=b;a=new a(b);S=null;return a}
var T=class{constructor(a,b,c){a||(a=S);S=null;var d=this.constructor.h;a||(a=d?[d]:[]);this.l=(d?0:-1)-(this.constructor.g||0);this.g=void 0;this.i=a;a:{d=this.i.length;a=d-1;if(d&&(d=this.i[a],D(d))){this.j=a-this.l;this.h=d;break a}void 0!==b&&-1<b?(this.j=Math.max(b,a+1-this.l),this.h=void 0):this.j=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.j)a+=this.l,(d=this.i[a])?Array.isArray(d)&&A(d):this.i[a]=E;else{d=L(this);let e=d[a];e?Array.isArray(e)&&A(e):d[a]=E}}toJSON(){return H(this.i,
K)}};T.prototype.toString=function(){return this.i.toString()};let S;var U=class extends T{u(){return this}};Object.defineProperties(U,{[Symbol.hasInstance]:G(()=>{throw Error("Cannot perform instanceof checks for MutableMessage");})});function V(a,b,c,d,e,f){if(a=a.g&&a.g[c])if(Array.isArray(a)){d=f.o?A(a.slice()):a;F(b);if(null!=d){e=A([]);f=!1;for(a=0;a<d.length;a++)e[a]=d[a].i,f=f||B(e[a]);b.g||(b.g={});b.g[c]=d;d=e;if(!Array.isArray(d))throw Error("cannot mark non-array as mutable");f?Object.isFrozen(d)||(v?d[v]&=-9:void 0!==d.m&&(d.m&=-9)):y(d,8)}else b.g&&(b.g[c]=void 0),e=E;N(b,c,e)}else F(b),b.g||(b.g={}),e=null!=a?a.i:a,b.g[c]=a,N(b,c,e);else q&&d instanceof Uint8Array?e=d.length?new u(new Uint8Array(d)):t||(t=new u(null)):
(Array.isArray(d)&&(e?C(d):Array.isArray(d)&&z(d)&1&&f.o&&(d=d.slice())),e=d),N(b,c,e)};class W extends U{u(a){if(a!==l)throw Error("requires a valid immutable API token");if(B(this.i)){({o:a}={o:!0});a={o:a};const c=B(this.i);if(c&&!a.o)throw Error("copyRepeatedFields must be true for frozen messages");const d=new this.constructor;this.s&&(d.s=this.s.slice());const e=this.i;for(let f=0;f<e.length;f++){const g=e[f];if(f===e.length-1&&D(g))for(b in g){const h=+b;Number.isNaN(h)?L(d)[b]=g[b]:V(this,d,h,g[b],c,a)}else V(this,d,f-this.l,g,c,a)}var b=d}else b=this;return b}}
Object.defineProperties(W,{[Symbol.hasInstance]:G(Object[Symbol.hasInstance])});var ha=class extends W{constructor(a){super(a,-1,fa)}},fa=[8];var ja=class extends W{constructor(a){super(a,-1,ia)}},ia=[17];var la=class extends W{constructor(a){super(a,-1,ka)}},ka=[27];var ma=class extends W{constructor(a){super(a)}};var oa=class extends W{constructor(a){super(a,-1,na)}},na=[1,2,3,6];var qa=class extends W{constructor(){super(void 0,-1,pa)}},pa=[12];/*

 SPDX-License-Identifier: Apache-2.0
*/
function X(a,b){a=a.getElementsByTagName("META");for(let c=0;c<a.length;++c)if(a[c].getAttribute("name")===b)return a[c].getAttribute("content")||"";return""};function ra(a){if(!(0<a.g.length)){var b=X(a.body,"environment");for(const c of b.split("|"))c&&a.g.push(c)}}function Y(a,b){a=a.body;var c={detail:void 0};let d;"function"===typeof window.CustomEvent?d=new CustomEvent(b,c):(d=document.createEvent("CustomEvent"),d.initCustomEvent(b,!!c.bubbles,!!c.cancelable,c.detail));a.dispatchEvent(d)}
var sa=class{constructor(a){this.body=a;this.g=[];this.h={};X(a,"sampling_mod");var b=X(a,"namespace");if(!b){b="ns-"+(0,Math.random)().toString(36).substr(2,5);a:{var c=a.getElementsByTagName("META");for(let d=0;d<c.length;++d)if("namespace"===c[d].getAttribute("name")&&c[d].getAttribute("index")===(0).toString()){c[d].setAttribute("content",b);break a}c=a.querySelector("#mys-meta");c||(c=document.createElement("div"),c.id="mys-meta",c.style.position="absolute",c.style.display="none",a.appendChild(c));
a=document.createElement("META");a.setAttribute("name","namespace");a.setAttribute("content",b);a.setAttribute("index",(0).toString());c.appendChild(a)}}ra(this);!this.h.hasOwnProperty("META_LOCKED")&&(a=X(this.body,"custom_flags"))&&(this.h=JSON.parse(a))}addEventListener(a,b){this.body.addEventListener(a,b)}};var ta=class extends W{constructor(){super(void 0)}};function ua(a){var b=document;a=String(a);"application/xhtml+xml"===b.contentType&&(a=a.toLowerCase());return b.createElement(a)};function va(a){if(1>=a.h.offsetWidth||1>=a.h.offsetHeight)return!1;a.g.remove();Y(a.context,"spanReady");return!0}
var wa=class{constructor(a,b){this.context=a;this.j=b;this.h=ua("SPAN");this.g=ua("DIV");this.h.style.fontSize="6px";this.h.textContent="go";this.g.style.position="absolute";this.g.style.top="100%";this.g.style.left="100%";this.g.style.width="1px";this.g.style.height="0";this.g.style.overflow="hidden";this.g.style.visibility="hidden";this.g.appendChild(this.h)}wait(){if(!ea(this.j)&&(Y(this.context,"spanStart"),this.context.body.appendChild(this.g),!va(this)))return new Promise(a=>{const b=setInterval(()=>
{va(this)&&(clearInterval(b),a())},da(this.j))})}};var xa=class{constructor(a,b){this.context=a;this.h=Q(b,la,1);this.g=Q(b,ha,12)||new ha;Q(this.h,ja,10)||new ja}};var ya=class{constructor(){this.channel=3;(this.g=!(!window.mys||!window.mys.pingback))&&this.setData(43,Date.now()-window.mys.pingback.getBaseTime())}setAttribute(a,b){this.g&&window.mys.pingback.setAttribute(a,b)}setData(a,b){this.g&&window.mys.pingback.setData(a,b,this.channel)}send(a){this.g&&window.mys.pingback.send(a)}};function za(a){a.g&=-31}function Z(a,b){a.g|=b}var Aa=class{constructor(a,b){this.context=a;this.A=b;new qa;this.g=0;this.pingback=new ya}h(){}};function Ba(a){R(oa,X(a.context.body,"engine_msg")||"[]");return a.g.h()||Promise.resolve()}
var Ca=class{constructor(a,b,c,d){this.g=d(a,b,c);this.context=this.g.context}init(){za(this.g);Z(this.g,1);let a;null==(a=window.AFMA_Communicator)||a.addEventListener("onshow",()=>{Z(this.g,32)});let b=0;const c=this.context.body;c.addEventListener("browserRender",()=>{++b;if(1===b)Y(this.context,"overallStart"),Ba(this).then(()=>{Y(this.context,"overallQuiet")});else{var d=c.clientHeight;c.clientWidth&&d&&Ba(this)}})}};function Da(a){a.j.length=0;a.h=!0}function Ea(a,b){a.g=!0;const c=()=>{a.h=!1;const d=a.j.shift();return void 0===d?(a.g=!1,Promise.resolve()):Ea(a,d())};return b?b.then(c,()=>{if(a.h)return c();a.g=!1;return Promise.reject()}):c()}function Fa(a,b){for(const c of b)a.j.push(c);if(!a.g)return Ea(a)}var Ga=class{constructor(){this.h=this.g=!1;this.j=[]}};var Ha=class extends Aa{constructor(){super(...arguments);this.j=new Ga}h(){Da(this.j);return Fa(this.j,[()=>{},()=>{let a;var b=this.A;const c=new ta;P(c,3,100,0);P(c,4,1E4,0);P(c,5,!0,!1);O(b.g,3)&&P(c,2,!0,!1);b=b.context;ra(b);0<=b.g.indexOf("amp")&&P(c,2,!0,!1);c&&(a=(new wa(this.context,c)).wait());Y(this.context,"browserStart");Y(this.context,"browserStartEnd");za(this);Z(this,2);return a},()=>{Y(this.context,"browserReady");Y(this.context,"browserReadyEnd");Z(this,4);Y(this.context,"overallReady")},
()=>{Y(this.context,"browserQuiet");Y(this.context,"browserQuietEnd");Z(this,8)}])}};(function(a){let b=null;k("mys.engine.init",(c,d)=>{const e=R(ma,X(d,"render_config")||"[]");b=new Ca(c,d,e,a);b.init()});k("mys.engine.stage",()=>b?b.g.g:0)})(function(a,b,c){a=new sa(b);c=new xa(a,c);return new Ha(a,c)});}).call(this);
